# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('text', 'Text')], default='text', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'verbose_name': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerCategoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('answers', models.ManyToManyField(related_name='category', through='jeopardy.AnswerCategoryRelation', to='jeopardy.Answer')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategoryRoundRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Contestants',
                'verbose_name': 'Contestant',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contestants', models.ManyToManyField(related_name='game', to='jeopardy.Contestant')),
            ],
            options={
                'verbose_name_plural': 'Games',
                'verbose_name': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round_type', models.CharField(choices=[('normal', 'Normal'), ('chance', 'Chance')], default='normal', max_length=10)),
                ('categories', models.ManyToManyField(related_name='round', to='jeopardy.Category')),
            ],
            options={
                'verbose_name_plural': 'Rounds',
                'verbose_name': 'Round',
            },
        ),
        migrations.CreateModel(
            name='RoundGameRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Game')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Round')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.ManyToManyField(related_name='game', to='jeopardy.Round'),
        ),
        migrations.AddField(
            model_name='categoryroundrelation',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Round'),
        ),
        migrations.AddField(
            model_name='answercategoryrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeopardy.Category'),
        ),
    ]
